# Action name
name: Clang Tidy

# Here, this action will be enabled on all pushes.
# Modify this to fit your needs.
on:
    push

# Jobs section
jobs:
    # The job that will use the container image you just pushed to ghcr.io
    clang-tidy-job:
        runs-on: ubuntu-24.04
        container:
            image: ghcr.io/drlk/clang-tidy-image:v16
            credentials:
               username: drlk
               password: ${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                submodules: true
            - name: clang-tidy
              shell: sh
              run: |
                cmake --version
                clang-tidy --version
                g++ --version
                clang++ --version
                cd ./SimpleNetworkProtocol/build
                time cmake ..
                time cmake --build . -- -j12
                rm -r *
                export CC=clang
                export CXX=clang++
                time cmake -G "Ninja" -DCMAKE_CXX_CLANG_TIDY="clang-tidy;-header-filter=." ..
                time cmake --build .
